/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[6],{166:function(Ba,ua,r){function pa(Ra,Ka,xa,Ja){return Object(ca.b)(void 0,void 0,void 0,function(){var Ha,Pa,Ua,Qa,Ea,Ga,Va,Wa,Za;return Object(ca.d)(this,function(eb){switch(eb.label){case 0:return Ha=La.getDocument(),Pa=[1],[4,Object(ia.c)(Ka,{extension:"pdf"})];case 1:return Ua=eb.ea(),Qa=La.ra(),Va=(Ga=oa.a).Mga,[4,Ua.YB()];case 2:return Ea=Va.apply(Ga,[eb.ea().xfdfString,Ra]),Wa=!0,[4,Ha.Bf(Ua,Pa,Ra,Wa)];case 3:return eb.ea(),
[4,Ha.ng([Ra+1],Wa)];case 4:return eb.ea(),Za=Qa.qb().filter(function(fb){return fb.mK()&&fb.PageNumber===Ra}),Qa.Ah(Za,{force:!0,source:"contentEditTool"}),[4,Qa.UJ(Ea)];case 5:return eb.ea(),La.getDocument().HL(),La.GL(Ra),La.Ve(),ha(Ra),f(Ra,xa.galleys,Ja),f(Ra,xa.objects,Ja),[2]}})})}function ka(Ra){Ra=(new DOMParser).parseFromString(Ra,"text/html").documentElement.querySelector("body");Ra.querySelectorAll("p").forEach(function(Ka){Ka.querySelectorAll("span").forEach(function(Ha){var Pa=Ha.getAttribute("style");
Pa=ma(Pa,Ha.innerHTML);Ha.innerHTML=Pa});var xa=Ka.getAttribute("style"),Ja=Ka.innerHTML.replaceAll("<br>","");Ka.innerHTML=ma(xa,Ja)});return Ra.innerHTML.trim()}function ma(Ra,Ka){Ra.includes("bold")&&(Ka="<strong>"+Ka+"</strong>");Ra.includes("italic")&&(Ka="<em>"+Ka+"</em>");Ra.includes("text-decoration: underline")&&(Ka="<u>"+Ka+"</u>");return Ka}function ha(Ra){var Ka=La.ra(),xa=Ka.qb().filter(function(Ja){return Ja.Mh()&&Ja.PageNumber===Ra});Ka.Ah(xa,{force:!0,source:"contentEditTool"})}function da(Ra,
Ka){Ka.forEach(function(xa){Ma[Ra]||(Ma[Ra]=[]);Ma[Ra].find(function(Ja){return Ja.id===xa.id})||Ma[Ra].push(xa)})}function aa(Ra,Ka){Ka.forEach(function(xa){Ia[Ra]||(Ia[Ra]=[]);Ia[Ra].find(function(Ja){return Ja.id===xa.id})||Ia[Ra].push(xa)})}function x(Ra){var Ka=new DOMParser,xa=Ka.parseFromString(Ra,"text/xml");xa.querySelector("parsererror")&&(xa=Ka.parseFromString("<Root>"+Ra+"</Root>","text/xml"));xa.querySelectorAll("a").forEach(function(Ja){var Ha=Ja.childNodes[0];Array.from(Ja.querySelectorAll("*")).find(function(Pa){return"u"===
Pa.tagName.toLowerCase()})||(Ja=document.createElement("u"),Ha.after(Ja),Ja.appendChild(Ha))});return(new XMLSerializer).serializeToString(xa)}function y(Ra,Ka,xa,Ja){this.top=Ra;this.left=Ka;this.bottom=xa;this.right=Ja;this.topVal=function(){return Math.round(this.top)};this.bottomVal=function(){return Math.round(this.bottom)};this.leftVal=function(){return Math.round(this.left)};this.rightVal=function(){return Math.round(this.right)};this.height=function(){return Math.round(Math.abs(this.top-this.bottom))};
this.width=function(){return Math.round(this.right-this.left)};this.bR=function(Ha){return this.topVal()!==Ha.topVal()||this.leftVal()!==Ha.leftVal()||this.bottomVal()!==Ha.bottomVal()||this.rightVal()!==Ha.rightVal()}}function h(Ra,Ka,xa,Ja,Ha){this.id=Ra;this.pagenum=Ka;this.galleysContents=xa;this.contents=Ja;this.galleyBox=Ha;Object(va.g)(Ia)}function e(Ra,Ka,xa,Ja){this.id=Ka;this.type=Ra;this.bbox=xa;this.pagenum=Ja}function b(Ra,Ka,xa,Ja,Ha){this.id=Ra;this.pagecount=Ka;this.pageBBox=xa;this.galleys=
Ja;this.objects=Ha}function a(Ra,Ka,xa,Ja,Ha){var Pa=[];(new DOMParser).parseFromString(Ja,"text/html").documentElement.querySelectorAll("p").forEach(function(Ga,Va){Pa[Va]=Ga.innerHTML});xa=(new DOMParser).parseFromString(xa,"text/html");var Ua=null;xa.documentElement.querySelectorAll("p").forEach(function(Ga,Va){Va<Pa.length?(Ga.innerHTML=Pa[Va],Ua=Ga.getAttribute("style"),Ua=Ua.replace("font:italic","font:normal"),Ua=Ua.replace(" bold "," normal "),Ua=Ua.replace("underline:1;","underline:0;"),
Ga.setAttribute("style",Ua)):Ga.remove()});for(Ja=xa.documentElement.querySelectorAll("p").length;Ja<Pa.length;Ja++){var Qa=document.createElement("p");Qa.setAttribute("id","0");Qa.innerHTML=Pa[Ja];null!=Ua&&Qa.setAttribute("style",Ua);xa.documentElement.querySelector("body").appendChild(Qa)}xa=xa.documentElement.querySelector("body").innerHTML;var Ea="";Ia[Ra].forEach(function(Ga){Ga.id===Ha&&(Ea=Ga)});if(""===Ea)return"";Ka="<DOC id='"+Ka.id+"' pagecount='"+Ka.pagecount+"'>";Ka=Ka+("<STORY galley_ids='"+
Ha+"' pagenum='"+Ra+"'><galleys>")+(Ea.galleysContents+"</galleys>");Ea.contents=xa;Ka=Ka+xa+"\n</STORY>";return Ka+="</DOC>"}function f(Ra,Ka,xa){var Ja=[],Ha=La.getDocument(),Pa=null;Ka.forEach(function(Ua){if(Ua instanceof e){var Qa=Ha.Tn(Ra,Ua.bbox.leftVal(),Ua.bbox.topVal());var Ea=Qa.x;var Ga=Qa.y;var Va=Ha.Tn(Ra,Ua.bbox.rightVal(),Ua.bbox.bottomVal());Qa=Va.x;Va=Va.y}else if(Ua instanceof h)Qa=Ha.Tn(Ra,Ua.galleyBox.leftVal(),Ua.galleyBox.topVal()),Ea=Qa.x,Ga=Qa.y,Va=Ha.Tn(Ra,Ua.galleyBox.rightVal(),
Ua.galleyBox.bottomVal()),Qa=Va.x,Va=Va.y;else return;var Wa=new window.Core.Annotations.RectangleAnnotation,Za=ta.a.OBJECT;Ua instanceof h&&(Za=ta.a.TEXT);Wa.tja(Ua,Za);Wa.PageNumber=Ua.pagenum;Wa.X=Ea;Wa.Y=Ga;Wa.Width=Qa-Ea;Wa.Height=Va-Ga;Wa.StrokeColor=new fa.a("#3183C8");Wa.FillColor=new fa.a(255,255,255,.01);Wa.Style="dash";Wa.Dashes="4,3";Wa.IB();Wa.selectionModel=la.a;Ja.push(Wa);"undefined"!==typeof xa&&xa===Ua.id&&(Pa=Wa)});Ka=La.ra();Ka.Ig(Ja);Pa&&Ka.rg(Pa);Ka.de(Ja)}function n(Ra,Ka,xa){return Object(ca.b)(this,
void 0,void 0,function(){var Ja,Ha,Pa,Ua,Qa;return Object(ca.d)(this,function(Ea){switch(Ea.label){case 0:Ja=Ra.data;Pa=Ja.cmd;switch(Pa){case "isReady":return[3,1];case "initialiseInfixServer":return[3,3];case "exportFile":return[3,4];case "importText":return[3,5];case "transformObject":return[3,5];case "deleteObject":return[3,6]}return[3,7];case 1:return[4,Object(qa.b)()];case 2:return Ua=Ea.ea(),wa.postMessage({cmd:"initialiseInfixServer",l:Ua}),[3,7];case 3:return(Qa=z(Ja.resultsXML))?Ka():xa("License key does not have content edit permission"),
[3,7];case 4:return Ja.exportPerformed?w(Ja.pageNumber,Ja.exportXML,Ja.objectXML,Ja.resultsXML):(Ha=Ca[Ja.pageNumber],aa(Ja.pageNumber,Ha.galleys),da(Ja.pageNumber,Ha.objects),ha(Ja.pageNumber),f(Ja.pageNumber,Ha.galleys),f(Ja.pageNumber,Ha.objects)),[3,7];case 5:return Ha=Ca[Ja.pageNumber],ba(Ja.pageNumber,Ja.resultsXML),pa(Ja.pageNumber,Ja.pdfBuffer,Ha,Ja.id),[3,7];case 6:return Ha=Ca[Ja.pageNumber],ba(Ja.pageNumber,Ja.resultsXML),Ha.galleys=Ha.galleys.filter(function(Ga){return Ga.id!==Ja.id}),
Ha.objects=Ha.objects.filter(function(Ga){return Ga.id!==Ja.id}),pa(Ja.pageNumber,Ja.pdfBuffer,Ha),[3,7];case 7:return[2]}})})}function z(Ra){Ra=new Uint8Array(Ra);var Ka=(new TextDecoder("utf-8")).decode(Ra);Ra=!1;Ka=(new DOMParser).parseFromString(Ka,"text/xml").getElementsByTagName("LicenseCheck");null!==Ka&&0<Ka.length&&(Ka=Ka[0].getElementsByTagName("Status")[0].innerHTML,"error"!==Ka&&"ok"===Ka&&(Ra=!0));return Ra}function w(Ra,Ka,xa,Ja){var Ha=new Uint8Array(Ka),Pa=new TextDecoder("utf-8");
Ka=Pa.decode(Ha);Ha=new Uint8Array(xa);xa=Pa.decode(Ha);Ha=new Uint8Array(Ja);Ja=Pa.decode(Ha);Ca[Ra]=ja(Ra,Ka,xa,Ja);Ja=Ca[Ra];aa(Ra,Ja.galleys);da(Ra,Ja.objects);ha(Ra);f(Ra,Ja.galleys);f(Ra,Ja.objects)}function ea(Ra,Ka){Ra=parseFloat(Ra);return isNaN(Ka)||Ka<Ra?Ra:Ka}function ja(Ra,Ka,xa,Ja){var Ha;var Pa=new DOMParser;Ja=Pa.parseFromString(Ja,"text/xml");Array.prototype.slice.call(Ja.getElementsByTagName("BBox")).forEach(function(Ea){if("CropBox"===Ea.getAttribute("Name")){var Ga=parseFloat(Ea.getElementsByTagName("Top").item(0).innerHTML),
Va=parseFloat(Ea.getElementsByTagName("Bottom").item(0).innerHTML),Wa=parseFloat(Ea.getElementsByTagName("Left").item(0).innerHTML);Ea=parseFloat(Ea.getElementsByTagName("Right").item(0).innerHTML);Ha=new y(Ga,Wa,Va,Ea)}});Pa=new DOMParser;Ja=Pa.parseFromString(Ka,"text/xml");var Ua=[];Array.prototype.slice.call(Ja.getElementsByTagName("STORY")).forEach(function(Ea){var Ga=Ea.getAttribute("galley_ids"),Va=Array.prototype.slice.call(Ea.getElementsByTagName("g"))[0],Wa=Va.getAttribute("bbox").split(" ");
Wa=new y(parseFloat(Wa[0]),parseFloat(Wa[1]),parseFloat(Wa[2]),parseFloat(Wa[3]));Va=Va.innerHTML;var Za=Array.prototype.slice.call(Ea.getElementsByTagName("galleys"))[0];Za.parentNode.removeChild(Za);Ea=Ea.innerHTML;Ea=(new DOMParser).parseFromString(Ea,"text/html").documentElement.querySelector("body").innerHTML.trim();Ga=new h(Ga,Ra,Va,Ea,Wa);Ua.push(Ga)});Pa=new DOMParser;var Qa=[];Ka=Pa.parseFromString(xa,"text/xml").getElementsByTagName("Object");Array.prototype.slice.call(Ka).forEach(function(Ea){var Ga=
Ea.getAttribute("Type"),Va=Ea.getAttribute("OID");Ea=Array.prototype.slice.call(Ea.getElementsByTagName("Point"));var Wa=Number.NaN,Za=Number.NaN,eb=Number.NaN,fb=Number.NaN;Ea.forEach(function(hb){var mb=hb.getAttribute("Name");"TL"===mb?(Wa=ea(hb.getAttribute("Y"),Wa),eb=ea(hb.getAttribute("X"),eb)):"TR"===mb?(Wa=ea(hb.getAttribute("Y"),Wa),fb=ea(hb.getAttribute("X"),fb)):"BR"===mb?(Za=ea(hb.getAttribute("Y"),Za),fb=ea(hb.getAttribute("X"),fb)):"BL"===mb&&(Za=ea(hb.getAttribute("Y"),Za),eb=ea(hb.getAttribute("X"),
eb))});Ea=new y(Wa,eb,Za,fb);Ga=new e(Ga,Va,Ea,Ra);Qa.push(Ga)});Ka=Array.prototype.slice.call(Ja.getElementsByTagName("DOC"))[0].getAttribute("id");return new b(Ka,1,Ha,Ua,Qa)}function ba(Ra,Ka){var xa;Ka=(new TextDecoder("utf-8")).decode(Ka);var Ja=(new DOMParser).parseFromString(Ka,"text/xml");Ka=Ja.getElementsByTagName("Galley").item(0);if(null!=Ka){var Ha=Ka.getAttribute("id");Ka=Ja.getElementsByTagName("BBox");Ka=Array.prototype.slice.call(Ka);Ka.forEach(function(Qa){var Ea=Qa.getElementsByTagName("Top"),
Ga=parseFloat(Ea.item(0).innerHTML);Ea=Qa.getElementsByTagName("Left");var Va=parseFloat(Ea.item(0).innerHTML);Ea=Qa.getElementsByTagName("Bottom");var Wa=parseFloat(Ea.item(0).innerHTML);Ea=Qa.getElementsByTagName("Right");Qa=parseFloat(Ea.item(0).innerHTML);xa=new y(Ga,Va,Wa,Qa)});Ia[Ra].forEach(function(Qa){Qa.id===Ha&&!0===xa.bR(Qa.galleyBox)&&(Qa.galleyBox=xa)})}Ka=Ja.getElementsByTagName("Object").item(0);if(null!=Ka){var Pa=Ka.getAttribute("OID");Ka=Ja.getElementsByTagName("BBox");Ka=Array.prototype.slice.call(Ka);
Ka.forEach(function(Qa){var Ea=Qa.getElementsByTagName("Top"),Ga=parseFloat(Ea.item(0).innerHTML);Ea=Qa.getElementsByTagName("Left");var Va=parseFloat(Ea.item(0).innerHTML);Ea=Qa.getElementsByTagName("Bottom");var Wa=parseFloat(Ea.item(0).innerHTML);Ea=Qa.getElementsByTagName("Right");Qa=parseFloat(Ea.item(0).innerHTML);xa=new y(Ga,Va,Wa,Qa)});Ma[Ra].forEach(function(Qa){Qa.id===Pa&&!0===xa.bR(Qa.bbox)&&(Qa.bbox=xa)})}Ka=Ja.getElementsByTagName("NewParas").item(0);if(null!=Ka){var Ua=Ka.getAttribute("id");
Ia[Ra].forEach(function(Qa){if(Qa.id===Ua){var Ea="<Contents>"+Qa.contents;Ea+="</Contents>";var Ga=Array.prototype.slice.call(Ja.getElementsByTagName("NewPara"));Ea=(new DOMParser).parseFromString(Ea,"text/xml");var Va=Array.prototype.slice.call(Ea.getElementsByTagName("p"));Ga.forEach(function(Wa){var Za=parseFloat(Wa.innerHTML),eb=!1;Va.forEach(function(fb){var hb=fb.getAttribute("id");!1===eb&&"0"===hb&&(fb.setAttribute("id",Za),eb=!0)})});Qa.contents=Ea.getElementsByTagName("Contents").item(0).innerHTML}})}}
r.r(ua);var ca=r(1),ia=r(55),fa=r(7),la=r(470),na=r(37),qa=r(76),ra=r(2),ta=r(175),va=r(118),oa=r(6),wa=null,Da=null,Ia={},Ma={},Ca={},La;ua["default"]={Iga:function(Ra){return Object(ca.b)(void 0,void 0,void 0,function(){return Object(ca.d)(this,function(){Da||(La=Ra,Da=new Promise(function(Ka,xa){wa=new Worker(window.Core.getWorkerPath()+"contentEdit/InfixServerModule.js");wa.onmessage=function(Ja){n(Ja,Ka,xa)};wa.postMessage({cmd:"isReady"})}));return[2,Da]})})},Kga:function(Ra,Ka,xa){return Object(ca.b)(void 0,
void 0,void 0,function(){var Ja,Ha,Pa,Ua;return Object(ca.d)(this,function(Qa){switch(Qa.label){case 0:return ha(Ka),Ia[Ka]=[],Ma[Ka]=[],[4,Ra.Ge([Ka])];case 1:return Ja=Qa.ea(),Ha=new TextEncoder,Pa=Ha.encode(""),Ua=Pa.buffer,wa.postMessage({cmd:"exportFile",pageNumber:Ka,performExport:xa,pdfFile:Ja,tableData:Ua},[Ja,Ua]),[2]}})})},B7:function(Ra){return Object(ca.b)(void 0,void 0,void 0,function(){var Ka,xa,Ja,Ha,Pa,Ua,Qa,Ea;return Object(ca.d)(this,function(Ga){switch(Ga.label){case 0:return Ka=
Ra.id,xa=Ra.isText,Ja=Ra.pageNumber,Ha=La.getDocument(),[4,Ha.Ge([Ja])];case 1:return Pa=Ga.ea(),Ua=new TextEncoder,Qa=Ua.encode(""),Ea=Qa.buffer,wa.postMessage({cmd:"deleteObject",pdfFile:Pa,pageNumber:Ja,objectID:Ka,isText:xa,tableData:Ea},[Ea]),[2]}})})},cma:function(Ra){return Object(ca.b)(void 0,void 0,void 0,function(){var Ka,xa,Ja,Ha,Pa,Ua,Qa,Ea,Ga,Va,Wa,Za,eb;return Object(ca.d)(this,function(fb){switch(fb.label){case 0:return Ka=Ra.id,xa=Ra.position,Ja=xa.top,Ha=xa.left,Pa=xa.bottom,Ua=xa.right,
Qa=Ra.isText,Ea=Ra.pageNumber,Ga=La.getDocument(),[4,Ga.Ge([Ea])];case 1:return Va=fb.ea(),Wa=new TextEncoder,Za=Wa.encode(""),eb=Za.buffer,wa.postMessage({cmd:"transformObject",pdfFile:Va,pageNumber:Ea,objectID:Ka,isText:Qa,topVal:Ja,leftVal:Ha,bottomVal:Pa,rightVal:Ua,tableData:eb},[eb]),[2]}})})},uma:function(Ra,Ka){return Object(ca.b)(void 0,void 0,void 0,function(){var xa,Ja,Ha,Pa,Ua,Qa,Ea,Ga,Va,Wa,Za,eb,fb,hb,mb,yb,qb,vb;return Object(ca.d)(this,function(Eb){switch(Eb.label){case 0:xa=Ka.replaceAll("<p><br></p>",
"");Ja=x(xa);Ja=Ja.replace(/<span style="color: var\(--text-color\);">(.*?)<\/span>/g,"$1");Ha=Ra.Mu.id;Pa=Ra.PageNumber;Ua=Ca[Pa];Qa=Ua.galleys.find(function(Fb){return Fb.id===Ha});Ea=ka(Qa.contents);Ga=a(Pa,Ua,Ea,Ja,Ha);if(""===Ga)return[3,2];Va=new TextEncoder;Wa=Va.encode(Ga);Za=Wa.buffer;eb=Object(na.c)()||"https://www.pdftron.com/webfonts/v2/";fb=La.getDocument();return[4,fb.Ge([Pa])];case 1:return hb=Eb.ea(),Va=new TextEncoder,mb=Va.encode(""),yb=mb.buffer,wa.postMessage({cmd:"importText",
pdfFile:hb,pageNumber:Pa,webFontURL:eb,galleyId:Ha,importData:Za,tableData:yb},[Za,yb]),qb={},Qa&&(vb=Qa.galleyBox,qb={top:vb.top,left:vb.left,bottom:vb.bottom,right:vb.right}),Object(va.h)(Ea,Ja,qb),[3,3];case 2:Object(ra.g)("Unable to generate import XML"),Eb.label=3;case 3:return[2]}})})},Paa:function(Ra){if(Ra)return ka(Ra.contents);Object(ra.g)("Unable to extract document content")}}},470:function(Ba,ua,r){var pa=r(1);Ba=r(83);var ka=r(48);r=function(ma){function ha(){return null!==ma&&ma.apply(this,
arguments)||this}Object(pa.c)(ha,ma);ha.prototype.testSelection=function(da,aa,x){return ka.a.dl(da,aa,x)};return ha}(Ba.a);ua.a=r}}]);}).call(this || window)
