/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{444:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(471),ma=r(472),ha;(function(da){da[da.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";da[da.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";da[da.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ha||(ha={}));Ba=function(){function da(aa){this.aa=aa;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED}da.prototype.Gca=function(){var aa=this;return function(x,
y,h){return Object(pa.b)(aa,void 0,void 0,function(){var e,b,a,f,n,z,w,ea=this,ja;return Object(pa.d)(this,function(ba){switch(ba.label){case 0:if(this.state!==ha.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().ys();return[4,this.Uaa(e)];case 1:b=ba.ea(),a=this.T6(b),this.uI=null!==(ja=null===a||void 0===a?void 0:a.parse())&&void 0!==ja?ja:null,this.state=null===this.uI?ha.EXTERNAL_XFDF_NOT_AVAILABLE:ha.EXTERNAL_XFDF_AVAILABLE,ba.label=2;case 2:if(this.state===ha.EXTERNAL_XFDF_NOT_AVAILABLE)return h(x),
[2];f=new DOMParser;n=f.parseFromString(x,"text/xml");y.forEach(function(ca){ea.merge(n,ea.uI,ca-1)});z=new XMLSerializer;w=z.serializeToString(n);h(w);return[2]}})})}};da.prototype.nM=function(aa){this.Uaa=aa};da.prototype.oe=function(){this.uI=void 0;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED};da.prototype.T6=function(aa){return aa?Array.isArray(aa)?new ka.a(aa):"string"!==typeof aa?null:(new DOMParser).parseFromString(aa,"text/xml").querySelector("xfdf > add")?new ka.a(aa):new ma.a(aa):null};da.prototype.merge=
function(aa,x,y){var h=this;0===y&&(this.Yea(aa,x.op),this.$ea(aa,x.bI));var e=x.ca[y];e&&(this.afa(aa,e.nn),this.cfa(aa,e.f_,x.fw),this.bfa(aa,e.page,y),this.Zea(aa,e.ZR));e=this.aa.Kb();if(y===e-1){var b=x.fw;Object.keys(b).forEach(function(a){b[a].KJ||h.MV(aa,a,b[a])})}};da.prototype.Yea=function(aa,x){null!==x&&(aa=this.tv(aa),this.Gq(aa,"calculation-order",x))};da.prototype.$ea=function(aa,x){null!==x&&(aa=this.tv(aa),this.Gq(aa,"document-actions",x))};da.prototype.afa=function(aa,x){var y=this,
h=this.sv(aa.querySelector("xfdf"),"annots");Object.keys(x).forEach(function(e){y.Gq(h,'[name="'+e+'"]',x[e])})};da.prototype.cfa=function(aa,x,y){var h=this;if(0!==x.length){var e=this.tv(aa);x.forEach(function(b){var a=b.getAttribute("field"),f=y[a];f&&(h.MV(aa,a,f),h.Gq(e,"null",b))})}};da.prototype.MV=function(aa,x,y){var h=this.tv(aa);null!==y.ZB&&this.Gq(h,'ffield [name="'+x+'"]',y.ZB);aa=this.sv(aa.querySelector("xfdf"),"fields");x=x.split(".");this.xL(aa,x,0,y.value);y.KJ=!0};da.prototype.bfa=
function(aa,x,y){null!==x&&(aa=this.tv(aa),aa=this.sv(aa,"pages"),this.Gq(aa,'[number="'+(y+1)+'"]',x))};da.prototype.Zea=function(aa,x){Object.keys(x).forEach(function(y){(y=aa.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};da.prototype.xL=function(aa,x,y,h){if(y===x.length)x=document.createElementNS("","value"),x.textContent=h,this.Gq(aa,"value",x);else{var e=x[y];this.sv(aa,'[name="'+e+'"]',"field").setAttribute("name",e);aa=aa.querySelectorAll('[name="'+e+'"]');1===
aa.length?this.xL(aa[0],x,y+1,h):(e=this.H$(aa),this.xL(y===x.length-1?e:this.Tla(aa,e),x,y+1,h))}};da.prototype.H$=function(aa){for(var x=null,y=0;y<aa.length;y++){var h=aa[y];if(0===h.childElementCount||1===h.childElementCount&&"value"===h.children[0].tagName){x=h;break}}return x};da.prototype.Tla=function(aa,x){for(var y=0;y<aa.length;y++)if(aa[y]!==x)return aa[y];return null};da.prototype.Gq=function(aa,x,y){x=aa.querySelector(x);null!==x&&aa.removeChild(x);aa.appendChild(y)};da.prototype.tv=
function(aa){var x=aa.querySelector("pdf-info");if(null!==x)return x;x=this.sv(aa.querySelector("xfdf"),"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};da.prototype.sv=function(aa,x,y){var h=aa.querySelector(x);if(null!==h)return h;h=document.createElementNS("",y||x);aa.appendChild(h);return h};return da}();ua["default"]=Ba},456:function(Ba,ua){Ba=function(){function r(){}r.prototype.AA=function(pa){var ka=
{op:null,bI:null,fw:{},ca:{}};pa=(new DOMParser).parseFromString(pa,"text/xml");ka.op=pa.querySelector("pdf-info calculation-order");ka.bI=pa.querySelector("pdf-info document-actions");ka.fw=this.Vfa(pa);ka.ca=this.gga(pa);return ka};r.prototype.Vfa=function(pa){var ka=pa.querySelector("fields");pa=pa.querySelectorAll("pdf-info > ffield");if(null===ka&&null===pa)return{};var ma={};this.p4(ma,ka);this.n4(ma,pa);return ma};r.prototype.p4=function(pa,ka){if(null!==ka&&ka.children){for(var ma=[],ha=0;ha<
ka.children.length;ha++){var da=ka.children[ha];ma.push({name:da.getAttribute("name"),element:da})}for(;0!==ma.length;)for(ka=ma.shift(),ha=0;ha<ka.element.children.length;ha++)da=ka.element.children[ha],"value"===da.tagName?pa[ka.name]={value:da.textContent,ZB:null,KJ:!1}:da.children&&ma.push({name:ka.name+"."+da.getAttribute("name"),element:da})}};r.prototype.n4=function(pa,ka){ka.forEach(function(ma){var ha=ma.getAttribute("name");pa[ha]?pa[ha].ZB=ma:pa[ha]={value:null,ZB:ma,KJ:!1}})};r.prototype.gga=
function(pa){var ka=this,ma={};pa.querySelectorAll("pdf-info widget").forEach(function(ha){var da=parseInt(ha.getAttribute("page"),10)-1;ka.$C(ma,da);ma[da].f_.push(ha)});pa.querySelectorAll("pdf-info page").forEach(function(ha){var da=parseInt(ha.getAttribute("number"),10)-1;ka.$C(ma,da);ma[da].page=ha});this.zT(pa).forEach(function(ha){var da=parseInt(ha.getAttribute("page"),10),aa=ha.getAttribute("name");ka.$C(ma,da);ma[da].nn[aa]=ha});this.lT(pa).forEach(function(ha){var da=parseInt(ha.getAttribute("page"),
10);ha=ha.textContent;ka.$C(ma,da);ma[da].ZR[ha]=!0});return ma};r.prototype.$C=function(pa,ka){pa[ka]||(pa[ka]={nn:{},ZR:{},f_:[],page:null})};return r}();ua.a=Ba},471:function(Ba,ua,r){var pa=r(1),ka=r(0);r.n(ka);Ba=function(ma){function ha(da){var aa=ma.call(this)||this;aa.t$=Array.isArray(da)?da:[da];return aa}Object(pa.c)(ha,ma);ha.prototype.parse=function(){var da=this,aa={op:null,bI:null,fw:{},ca:{}};this.t$.forEach(function(x){aa=Object(ka.merge)(aa,da.AA(x))});return aa};ha.prototype.zT=
function(da){var aa=[];da.querySelectorAll("add > *").forEach(function(x){aa.push(x)});da.querySelectorAll("modify > *").forEach(function(x){aa.push(x)});return aa};ha.prototype.lT=function(da){return da.querySelectorAll("delete > *")};return ha}(r(456).a);ua.a=Ba},472:function(Ba,ua,r){var pa=r(1);Ba=function(ka){function ma(ha){var da=ka.call(this)||this;da.u$=ha;return da}Object(pa.c)(ma,ka);ma.prototype.parse=function(){return this.AA(this.u$)};ma.prototype.zT=function(ha){return ha.querySelectorAll("annots > *")};
ma.prototype.lT=function(){return[]};return ma}(r(456).a);ua.a=Ba}}]);}).call(this || window)
