/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{429:function(Ba,ua,r){r.r(ua);r.d(ua,"ByteRangeRequest",function(){return z});var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),ha=r(147);Ba=r(94);var da=r(245),aa=r(73),x=r(70),y=r(244),h=r(165);r=r(372);var e=[],b=[],a=window,f=function(){return function(){this.gm=1}}(),n;(function(ea){ea[ea.UNSENT=0]="UNSENT";ea[ea.DONE=4]="DONE"})(n||(n={}));var z=function(){function ea(ja,ba,ca,ia){var fa=this;this.url=ja;this.range=ba;this.df=ca;
this.withCredentials=ia;this.W1=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);a.Uint8Array&&(this.request.responseType="arraybuffer");ia&&(this.request.withCredentials=ia);w.DISABLE_RANGE_HEADER||(Object(ka.isUndefined)(ba.stop)?this.request.setRequestHeader("Range","bytes="+ba.start):this.request.setRequestHeader("Range",["bytes=",ba.start,"-",ba.stop-1].join("")));ca&&Object.keys(ca).forEach(function(la){fa.request.setRequestHeader(la,ca[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ea.prototype.start=function(ja){var ba=this,ca=this.request;ca.onreadystatechange=function(){if(ba.aborted)return ba.status=y.a.ABORTED,ja({code:y.a.ABORTED});if(this.readyState===ba.W1.DONE){ba.AC();var ia=0===window.document.URL.indexOf("file:///");200===ca.status||206===ca.status||ia&&0===ca.status?(ia=a.QT(this),ba.ZM(ia,ja)):(ba.status=
y.a.ERROR,ja({code:ba.status,status:ba.status}))}};this.request.send(null);this.status=y.a.STARTED};ea.prototype.ZM=function(ja,ba){this.status=y.a.SUCCESS;if(ba)return ba(!1,ja)};ea.prototype.abort=function(){this.AC();this.aborted=!0;this.request.abort()};ea.prototype.AC=function(){var ja=Object(h.c)(this.url,this.range,b);-1!==ja&&b.splice(ja,1);if(0<e.length){ja=e.shift();var ba=new ea(ja.url,ja.range,this.df,this.withCredentials);ja.request=ba;b.push(ja);ba.start(Object(h.d)(ja))}};ea.prototype.extend=
function(ja){var ba=Object.assign({},this,ja.prototype);ba.constructor=ja;return ba};return ea}(),w=function(ea){function ja(ba,ca,ia,fa,la){ia=ea.call(this,ba,ia,fa)||this;ia.jm={};ia.cB=ca;ia.url=ba;ia.DISABLE_RANGE_HEADER=!1;ia.Tx=z;ia.VN=3;ia.df=la||{};return ia}Object(pa.c)(ja,ea);ja.prototype.Mv=function(ba,ca,ia){var fa=-1===ba.indexOf("?")?"?":"&";switch(ia){case !1:case x.a.NEVER_CACHE:ba=ba+fa+"_="+Object(ka.uniqueId)();break;case !0:case x.a.CACHE:ba=ba+fa+"_="+ca.start+","+(Object(ka.isUndefined)(ca.stop)?
"":ca.stop)}return ba};ja.prototype.LR=function(ba,ca,ia,fa){void 0===ia&&(ia={});return new this.Tx(ba,ca,ia,fa)};ja.prototype.j$=function(ba,ca,ia,fa,la){for(var na=0;na<e.length;na++)if(Object(ka.isEqual)(e[na].range,ca)&&Object(ka.isEqual)(e[na].url,ba))return e[na].Mg.push(fa),e[na].FD++,null;for(na=0;na<b.length;na++)if(Object(ka.isEqual)(b[na].range,ca)&&Object(ka.isEqual)(b[na].url,ba))return b[na].Mg.push(fa),b[na].FD++,null;ia={url:ba,range:ca,cB:ia,Mg:[fa],FD:1};if(0===e.length&&b.length<
this.VN)return b.push(ia),ia.request=this.LR(ba,ca,la,this.withCredentials),ia;e.push(ia);return null};ja.prototype.co=function(ba,ca,ia){var fa=this.Mv(ba,ca,this.cB);(ba=this.j$(fa,ca,this.cB,ia,this.df))&&ba.request.start(Object(h.d)(ba));return function(){var la=Object(h.c)(fa,ca,b);if(-1!==la){var na=--b[la].FD;0===na&&b[la].request&&b[la].request.abort()}else la=Object(h.c)(fa,ca,e),-1!==la&&(na=--e[la].FD,0===na&&e.splice(la,1))}};ja.prototype.qT=function(){return{start:-ha.a}};ja.prototype.Oca=
function(){var ba=-(ha.a+ha.e);return{start:ba-ha.d,end:ba}};ja.prototype.nt=function(ba){var ca=this;this.iB=!0;var ia=ha.a;this.co(this.url,this.qT(),function(fa,la,na){function qa(){var ra=ca.Zd.mT();ca.co(ca.url,ra,function(ta,va){if(ta)return Object(ma.j)("Error loading central directory: "+ta),ba(ta);va=Object(aa.a)(va);if(va.length!==ra.stop-ra.start)return ba("Invalid XOD file: Zip central directory data is wrong size! Should be "+(ra.stop-ra.start)+" but is "+va.length);ca.Zd.jX(va);ca.DH=
!0;ca.iB=!1;return ba(!1)})}if(fa)return Object(ma.j)("Error loading end header: "+fa),ba(fa,la,na);la=Object(aa.a)(la);if(la.length!==ia)return ba("Invalid XOD file: Zip end header data is wrong size!");try{ca.Zd=new da.a(la)}catch(ra){return ba(ra)}ca.Zd.rea?ca.co(ca.url,ca.Oca(),function(ra,ta){if(ra)return Object(ma.j)("Error loading zip64 header: "+ra),ba(ra);ta=Object(aa.a)(ta);ca.Zd.Kea(ta);qa()}):qa()})};ja.prototype.MT=function(ba){ba(Object.keys(this.Zd.Dn))};ja.prototype.AL=function(ba,
ca){var ia=this;if(this.Zd.BR(ba)){var fa=this.Zd.uC(ba);if(fa in this.jm){var la=this.Wh[ba];la.Wr=this.jm[fa];la.Wr.gm++;la.cancel=la.Wr.cancel}else{var na=this.Zd.aba(ba),qa=this.co(this.url,na,function(ta,va){ta?(Object(ma.j)('Error loading part "'+ba+'": '+ta),ia.co(ia.url,na,function(oa,wa){if(oa)return ca(oa,ba);ia.nX(wa,na,fa,ba,ca)})):ia.nX(va,na,fa,ba,ca)}),ra=this.Wh[ba];ra&&(ra.pZ=!0,ra.cancel=function(){ra.Wr.gm--;0===ra.Wr.gm&&(qa(),delete ia.jm[fa])},this.jm[fa]=new f(fa),ra.Wr=this.jm[fa],
ra.Wr.cancel=ra.cancel)}}else delete this.Wh[ba],ca(Error('File not found: "'+ba+'"'),ba)};ja.prototype.nX=function(ba,ca,ia,fa,la){if(ba.length!==ca.stop-ca.start)la(Error("Part data is wrong size!"),fa);else{do{if(!this.jm[ia])return;fa=this.jm[ia].gm;for(var na=ca.Hq.length,qa=0;qa<na;++qa){var ra=ca.Hq[qa];la(!1,ra.Dq,ba["string"===typeof ba?"substring":"subarray"](ra.start,ra.stop),this.Zd.PU(ra.Dq));ra.Dq in this.Wh&&delete this.Wh[ra.Dq]}}while(fa!==this.jm[ia].gm);delete this.jm[ia]}};ja.DISABLE_RANGE_HEADER=
!1;ja.VN=3;return ja}(Ba.a);(function(ea){function ja(ba,ca,ia){var fa=ea.call(this)||this,la;for(la in ba)fa[la]=ba[la];fa.Spa=ba;fa.startOffset=ca;fa.endOffset=ia;fa.LR=function(na,qa,ra,ta){Object(ka.isUndefined)(qa.stop)?(qa.start+=fa.endOffset,qa.stop=fa.endOffset):(qa.start+=fa.startOffset,qa.stop+=fa.startOffset);na=fa.Mv(fa.url,qa,fa.cB);return new ba.Tx(na,qa,ra,ta)};return fa}Object(pa.c)(ja,ea);return ja})(w);Object(r.a)(w);Object(r.b)(w);ua["default"]=w}}]);}).call(this || window)
