/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[12],{443:function(Ba,ua,r){function pa(ca){ca.Ga();ca.advance();var ia=ca.current.textContent;ca.Va();return ia}function ka(ca){var ia=[];for(ca.Ga();ca.advance();){var fa=ca.La();"field"===fa?ia.push(String(ca.ga("name"))):Object(a.j)("unrecognised field list element: "+fa)}ca.Va();return ia}function ma(ca,ia){return ia?"false"!==ca:"true"===ca}function ha(ca,ia){var fa=ca.La();switch(fa){case "javascript":return{name:"JavaScript",
javascript:ca.current.textContent};case "uri":return{name:"URI",uri:ca.ga("uri")};case "goto":fa=null;ca.Ga();if(ca.advance()){var la=ca.ga("fit");fa={page:ca.ga("page"),fit:la};if("0"===fa.page)Object(a.j)("null page encountered in dest");else switch(ia=ia(Number(fa.page)),la){case "Fit":case "FitB":break;case "FitH":case "FitBH":fa.top=ia.na({x:0,y:ca.ga("top")||0}).y;break;case "FitV":case "FitBV":fa.left=ia.na({x:ca.ga("left")||0,y:0}).x;break;case "FitR":la=ia.na({x:ca.ga("left")||0,y:ca.ga("top")||
0});ia=ia.na({x:ca.ga("right")||0,y:ca.ga("bottom")||0});ia=new z.d(la.x,la.y,ia.x,ia.y);fa.top=ia.y1;fa.left=ia.x1;fa.bottom=ia.y2;fa.right=ia.x2;break;case "XYZ":la=ia.na({x:ca.ga("left")||0,y:ca.ga("top")||0});fa.top=la.y;fa.left=la.x;fa.zoom=ca.ga("zoom")||0;break;default:Object(a.j)("unknown dest fit: "+la)}fa={name:"GoTo",dest:fa}}else Object(a.j)("missing dest in GoTo action");ca.Va();return fa;case "submit-form":fa={name:"SubmitForm",url:ca.ga("url"),format:ca.ga("format"),method:ca.ga("method")||
"POST",exclude:ma(ca.ga("exclude"),!1)};ia=ca.ga("flags");fa.flags=ia?ia.split(" "):[];for(ca.Ga();ca.advance();)switch(ia=ca.La(),ia){case "fields":fa.fields=ka(ca);break;default:Object(a.j)("unrecognised submit-form child: "+ia)}ca.Va();return fa;case "reset-form":fa={name:"ResetForm",exclude:ma(ca.ga("exclude"),!1)};for(ca.Ga();ca.advance();)switch(ia=ca.La(),ia){case "fields":fa.fields=ka(ca);break;default:Object(a.j)("unrecognised reset-form child: "+ia)}ca.Va();return fa;case "hide":fa={name:"Hide",
hide:ma(ca.ga("hide"),!0)};for(ca.Ga();ca.advance();)switch(ia=ca.La(),ia){case "fields":fa.fields=ka(ca);break;default:Object(a.j)("unrecognised hide child: "+ia)}ca.Va();return fa;case "named":return{name:"Named",action:ca.ga("name")};default:Object(a.j)("Encountered unexpected action type: "+fa)}return null}function da(ca,ia,fa){var la={};for(ca.Ga();ca.advance();){var na=ca.La();switch(na){case "action":na=ca.ga("trigger");if(ia?-1!==ia.indexOf(na):1){la[na]=[];for(ca.Ga();ca.advance();){var qa=
ha(ca,fa);Object(f.isNull)(qa)||la[na].push(qa)}ca.Va()}else Object(a.j)("encountered unexpected trigger on field: "+na);break;default:Object(a.j)("encountered unknown action child: "+na)}}ca.Va();return la}function aa(ca){return new w.a(ca.ga("r")||0,ca.ga("g")||0,ca.ga("b")||0,ca.ga("a")||1)}function x(ca,ia){var fa=ca.ga("name"),la=ca.ga("type")||"Type1",na=ca.ga("size"),qa=ia.na({x:0,y:0});na=ia.na({x:Number(na),y:0});ia=qa.x-na.x;qa=qa.y-na.y;fa={name:fa,type:la,size:Math.sqrt(ia*ia+qa*qa)||
0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(ca.Ga();ca.advance();)switch(la=ca.La(),la){case "stroke-color":fa.strokeColor=aa(ca);break;case "fill-color":fa.fillColor=aa(ca);break;default:Object(a.j)("unrecognised font child: "+la)}ca.Va();return fa}function y(ca){var ia=[];for(ca.Ga();ca.advance();){var fa=ca.La();switch(fa){case "option":fa=ia;var la=fa.push;var na=ca;na={value:na.ga("value"),displayValue:na.ga("display-value")||void 0};la.call(fa,na);break;default:Object(a.j)("unrecognised options child: "+
fa)}}ca.Va();return ia}function h(ca,ia){var fa=ca.ga("name"),la={type:ca.ga("type"),quadding:ca.ga("quadding")||"Left-justified",maxLen:ca.ga("max-len")||-1},na=ca.ga("flags");Object(f.isString)(na)&&(la.flags=na.split(" "));for(ca.Ga();ca.advance();)switch(na=ca.La(),na){case "actions":la.actions=da(ca,["C","F","K","V"],function(){return ia});break;case "default-value":la.defaultValue=pa(ca);break;case "font":la.font=x(ca,ia);break;case "options":la.options=y(ca);break;default:Object(a.j)("unknown field child: "+
na)}ca.Va();return new window.Annotations.ha.ma(fa,la)}function e(ca,ia){switch(ca.type){case "Tx":try{if(Object(ja.c)(ca.actions))return new n.a.DatePickerWidgetAnnotation(ca,ia)}catch(fa){Object(a.j)(fa)}return new n.a.TextWidgetAnnotation(ca,ia);case "Ch":return ca.flags.get(ba.WidgetFlags.COMBO)?new n.a.ChoiceWidgetAnnotation(ca,ia):new n.a.ListWidgetAnnotation(ca,ia);case "Btn":return ca.flags.get(ba.WidgetFlags.PUSH_BUTTON)?new n.a.PushButtonWidgetAnnotation(ca,ia):ca.flags.get(ba.WidgetFlags.RADIO)?
new n.a.RadioButtonWidgetAnnotation(ca,ia):new n.a.CheckButtonWidgetAnnotation(ca,ia);case "Sig":return new n.a.SignatureWidgetAnnotation(ca,ia);default:Object(a.j)("Unrecognised field type: "+ca.type)}return null}function b(ca,ia,fa,la){var na=[],qa={};ca.Ga();var ra=[],ta={},va=[];Object(ea.a)(function(){if(ca.advance()){var oa=ca.La();switch(oa){case "calculation-order":ra="calculation-order"===ca.La()?ka(ca):[];break;case "document-actions":ta=da(ca,["Init","Open"],ia);break;case "pages":oa=[];
for(ca.Ga();ca.advance();){var wa=ca.La();switch(wa){case "page":wa=oa;var Da=wa.push,Ia=ca,Ma=ia,Ca={number:Ia.ga("number")};for(Ia.Ga();Ia.advance();){var La=Ia.La();switch(La){case "actions":Ca.actions=da(Ia,["O","C"],Ma);break;default:Object(a.j)("unrecognised page child: "+La)}}Ia.Va();Da.call(wa,Ca);break;default:Object(a.j)("unrecognised page child: "+wa)}}ca.Va();va=oa;break;case "field":wa=h(ca,ia(1));qa[wa.name]=wa;break;case "widget":oa={border:{style:"Solid",width:1},backgroundColor:[],
fieldName:ca.ga("field"),page:ca.ga("page"),index:ca.ga("index")||0,rotation:ca.ga("rotation")||0,flags:[],isImporting:!0};(wa=ca.ga("appearance"))&&(oa.appearance=wa);(wa=ca.ga("flags"))&&(oa.flags=wa.split(" "));for(ca.Ga();ca.advance();)switch(wa=ca.La(),wa){case "rect":Da=ca;Ia=ia(Number(oa.page));wa=Ia.na({x:Da.ga("x1")||0,y:Da.ga("y1")||0});Da=Ia.na({x:Da.ga("x2")||0,y:Da.ga("y2")||0});wa=new z.d(wa.x,wa.y,Da.x,Da.y);wa.normalize();oa.rect={x1:wa.x1,y1:wa.y1,x2:wa.x2,y2:wa.y2};break;case "border":wa=
ca;Da={style:wa.ga("style")||"Solid",width:wa.ga("width")||1,color:[0,0,0]};for(wa.Ga();wa.advance();)switch(Ia=wa.La(),Ia){case "color":Da.color=aa(wa);break;default:Object(a.j)("unrecognised border child: "+Ia)}wa.Va();oa.border=Da;break;case "background-color":oa.backgroundColor=aa(ca);break;case "actions":oa.actions=da(ca,"E X D U Fo Bl PO PC PV PI".split(" "),ia);break;case "appearances":wa=ca;Da=Object(ja.b)(oa,"appearances");for(wa.Ga();wa.advance();)if(Ia=wa.La(),"appearance"===Ia){Ia=wa.ga("name");
Ma=Object(ja.b)(Da,Ia);Ia=wa;for(Ia.Ga();Ia.advance();)switch(Ca=Ia.La(),Ca){case "Normal":Object(ja.b)(Ma,"Normal").data=Ia.current.textContent;break;default:Object(a.j)("unexpected appearance state: ",Ca)}Ia.Va()}else Object(a.j)("unexpected appearances child: "+Ia);wa.Va();break;case "extra":wa=ca;Da=ia;Ia={};for(wa.Ga();wa.advance();)switch(Ma=wa.La(),Ma){case "font":Ia.font=x(wa,Da(1));break;default:Object(a.j)("unrecognised extra child: "+Ma)}wa.Va();wa=Ia;wa.font&&(oa.font=wa.font);break;case "captions":Da=
ca;wa={};(Ia=Da.ga("Normal"))&&(wa.Normal=Ia);(Ia=Da.ga("Rollover"))&&(wa.Rollover=Ia);(Da=Da.ga("Down"))&&(wa.Down=Da);oa.captions=wa;break;default:Object(a.j)("unrecognised widget child: "+wa)}ca.Va();(wa=qa[oa.fieldName])?(oa=e(wa,oa),na.push(oa)):Object(a.j)("ignoring widget with no corresponding field data: "+oa.fieldName);break;default:Object(a.j)("Unknown element encountered in PDFInfo: "+oa)}return!0}return!1},function(){ca.Va();fa({calculationOrder:ra,widgets:na,fields:qa,documentActions:ta,
pages:va,custom:[]})},la)}r.r(ua);r.d(ua,"parse",function(){return b});var a=r(2),f=r(0);r.n(f);var n=r(117),z=r(4),w=r(7),ea=r(21),ja=r(102),ba=r(17)}}]);}).call(this || window)
