/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{446:function(Ba,ua,r){r.r(ua);var pa=r(457),ka=r(116),ma=r(39),ha=r(74);Ba=function(){function da(){this.ob=this.se=this.Nb=this.ec=null;this.Le=!1}da.prototype.clear=function(){Object(ma.b)(this.ec);this.Nb="";Object(ma.b)(this.se);Object(ma.b)(this.ob);this.Le=!1};da.prototype.ed=function(){this.ec=[];this.se=[];this.ob=[];this.Le=!1};da.prototype.dA=function(aa){for(var x="",y=0,h,e,b;y<aa.length;)h=aa.charCodeAt(y),9===
h?(x+=String.fromCharCode(10),y++):128>h?(x+=String.fromCharCode(h),y++):191<h&&224>h?(e=aa.charCodeAt(y+1),x+=String.fromCharCode((h&31)<<6|e&63),y+=2):(e=aa.charCodeAt(y+1),b=aa.charCodeAt(y+2),x+=String.fromCharCode((h&15)<<12|(e&63)<<6|b&63),y+=3);return x};da.prototype.initData=function(aa){this.ec=[];this.se=[];this.ob=[];this.Le=!1;try{var x=new ha.a(aa);this.Nb="";x.Ga();if(!x.advance())return;var y=x.current.textContent;this.Nb=y=this.dA(y);Object(ma.b)(this.se);x.advance();y=x.current.textContent;
for(var h=y.split(","),e=Object(ka.a)(h);e.Vl();){var b=e.current;try{var a=parseInt(b.trim(),10);this.se.push(a)}catch(ba){}}Object(ma.b)(this.ec);x.advance();y=x.current.textContent;h=y.split(",");for(var f=Object(ka.a)(h);f.Vl();){b=f.current;try{a=parseFloat(b.trim()),this.ec.push(a)}catch(ba){}}Object(ma.b)(this.ob);x.advance();y=x.current.textContent;h=y.split(",");aa=[];x=[];y=0;for(var n=Object(ka.a)(h);n.Vl();){b=n.current;switch(b){case "Q":y=1;break;case "R":y=2;break;case "S":y=3;break;
default:y=0}if(y)aa.push(0),x.push(y);else try{a=parseFloat(b.trim()),aa.push(a),x.push(y)}catch(ba){return}}y=0;var z=aa.length;e=n=b=h=void 0;for(var w=f=0,ea=0;ea<z;){var ja=x[ea];if(0<ja)y=ja,++ea,3===y&&(f=aa[ea],w=aa[ea+1],ea+=2);else if(1===y)for(a=0;8>a;++a)this.ob.push(aa[ea++]);else 2===y?(h=aa[ea++],b=aa[ea++],n=aa[ea++],e=aa[ea++],this.ob.push(h),this.ob.push(b),this.ob.push(n),this.ob.push(b),this.ob.push(n),this.ob.push(e),this.ob.push(h),this.ob.push(e)):3===y&&(h=aa[ea++],b=f,n=aa[ea++],
e=w,this.ob.push(h),this.ob.push(b),this.ob.push(n),this.ob.push(b),this.ob.push(n),this.ob.push(e),this.ob.push(h),this.ob.push(e))}}catch(ba){return}this.Nb.length&&this.Nb.length===this.se.length&&8*this.Nb.length===this.ob.length&&(this.Le=!0)};da.prototype.ready=function(){return this.Le};da.prototype.sw=function(){var aa=new pa.a;if(!this.ec.length)return aa.Vg(this.ec,-1,this.Nb,this.ob,0),aa;aa.Vg(this.ec,1,this.Nb,this.ob,1);return aa};da.prototype.gf=function(){return this.ob};da.prototype.getData=
function(){return{m_Struct:this.ec,m_Str:this.Nb,m_Offsets:this.se,m_Quads:this.ob,m_Ready:this.Le}};return da}();ua["default"]=Ba},457:function(Ba,ua,r){var pa=r(86),ka=r(51),ma=r(473);Ba=function(){function ha(){this.ae=0;this.nb=this.Aa=this.Ze=null;this.Lc=0;this.$d=null}ha.prototype.ed=function(){this.ae=-1;this.Lc=0;this.$d=[]};ha.prototype.Vg=function(da,aa,x,y,h){this.ae=aa;this.Lc=h;this.$d=[];this.Ze=da;this.Aa=x;this.nb=y};ha.prototype.Bc=function(da){return this.ae===da.ae};ha.prototype.Vj=
function(){return Math.abs(this.Ze[this.ae])};ha.prototype.Rl=function(){return 0<this.Ze[this.ae]};ha.prototype.Pg=function(){var da=this.Rl()?6:10,aa=new ma.a;aa.Vg(this.Ze,this.ae+da,this.ae,this.Aa,this.nb,1);return aa};ha.prototype.gU=function(da){if(0>da||da>=this.Vj())return da=new ma.a,da.Vg(this.Ze,-1,-1,this.Aa,this.nb,0),da;var aa=this.Rl()?6:10,x=this.Rl()?5:11,y=new ma.a;y.Vg(this.Ze,this.ae+aa+x*da,this.ae,this.Aa,this.nb,1+da);return y};ha.prototype.Mn=function(){var da=this.ae+parseInt(this.Ze[this.ae+
1],10);if(da>=this.Ze.length)return da=new ha,da.Vg(this.Ze,-1,this.Aa,this.nb,0),da;var aa=new ha;aa.Vg(this.Ze,da,this.Aa,this.nb,this.Lc+1);return aa};ha.prototype.getBBox=function(da){if(this.Rl())da.x1=this.Ze[this.ae+2+0],da.y1=this.Ze[this.ae+2+1],da.x2=this.Ze[this.ae+2+2],da.y2=this.Ze[this.ae+2+3];else{for(var aa=1.79769E308,x=pa.a.MIN,y=1.79769E308,h=pa.a.MIN,e=0;4>e;++e){var b=this.Ze[this.ae+2+2*e],a=this.Ze[this.ae+2+2*e+1];aa=Math.min(aa,b);x=Math.max(x,b);y=Math.min(y,a);h=Math.max(h,
a)}da.x1=aa;da.y1=y;da.x2=x;da.y2=h}};ha.prototype.rC=function(){if(this.$d.length)return this.$d[0];var da=new ka.a,aa=new ka.a,x=new ma.a;x.ed();var y=this.Pg(),h=new ma.a;h.ed();for(var e=this.Pg();!e.Bc(x);e=e.Sg())h=e;x=Array(8);e=Array(8);y.He(0,x);da.x=(x[0]+x[2]+x[4]+x[6])/4;da.y=(x[1]+x[3]+x[5]+x[7])/4;h.He(h.Uj()-1,e);aa.x=(e[0]+e[2]+e[4]+e[6])/4;aa.y=(e[1]+e[3]+e[5]+e[7])/4;.01>Math.abs(da.x-aa.x)&&.01>Math.abs(da.y-aa.y)&&this.$d.push(0);da=Math.atan2(aa.y-da.y,aa.x-da.x);da*=180/3.1415926;
0>da&&(da+=360);this.$d.push(da);return 0};return ha}();ua.a=Ba},473:function(Ba,ua,r){var pa=r(457),ka=r(95),ma=r(86);Ba=function(){function ha(){this.Tk=this.Dd=0;this.nb=this.Aa=this.ec=null;this.Lc=0}ha.prototype.ed=function(){this.Tk=this.Dd=-1;this.Lc=0};ha.prototype.Vg=function(da,aa,x,y,h,e){this.Dd=aa;this.Tk=x;this.ec=da;this.Aa=y;this.nb=h;this.Lc=e};ha.prototype.Bc=function(da){return this.Dd===da.Dd};ha.prototype.Uj=function(){return parseInt(this.ec[this.Dd],10)};ha.prototype.Hi=function(){return parseInt(this.ec[this.Dd+
2],10)};ha.prototype.Ug=function(){return parseInt(this.ec[this.Dd+1],10)};ha.prototype.Rl=function(){return 0<this.ec[this.Tk]};ha.prototype.Rba=function(){return Math.abs(this.ec[this.Tk])};ha.prototype.Sg=function(){var da=this.Rl(),aa=da?5:11;if(this.Dd>=this.Tk+(da?6:10)+(this.Rba()-1)*aa)return aa=new ha,aa.Vg(this.ec,-1,-1,this.Aa,this.nb,0),aa;da=new ha;da.Vg(this.ec,this.Dd+aa,this.Tk,this.Aa,this.nb,this.Lc+1);return da};ha.prototype.gba=function(da){var aa=this.Uj();return 0>da||da>=aa?
-1:parseInt(this.ec[this.Dd+1],10)+da};ha.prototype.He=function(da,aa){da=this.gba(da);if(!(0>da)){var x=new pa.a;x.Vg(this.ec,this.Tk,this.Aa,this.nb,0);if(x.Rl()){var y=new ka.a;x.getBBox(y);x=y.y1<y.y2?y.y1:y.y2;y=y.y1>y.y2?y.y1:y.y2;da*=8;aa[0]=this.nb[da];aa[1]=x;aa[2]=this.nb[da+2];aa[3]=aa[1];aa[4]=this.nb[da+4];aa[5]=y;aa[6]=this.nb[da+6];aa[7]=aa[5]}else for(da*=8,x=0;8>x;++x)aa[x]=this.nb[da+x]}};ha.prototype.ge=function(da){var aa=new pa.a;aa.Vg(this.ec,this.Tk,this.Aa,this.nb,0);if(aa.Rl()){var x=
this.ec[this.Dd+3],y=this.ec[this.Dd+4];if(x>y){var h=x;x=y;y=h}h=new ka.a;aa.getBBox(h);aa=h.y1<h.y2?h.y1:h.y2;h=h.y1>h.y2?h.y1:h.y2;da[0]=x;da[1]=aa;da[2]=y;da[3]=aa;da[4]=y;da[5]=h;da[6]=x;da[7]=h}else for(x=this.Dd+3,y=0;8>y;++y)da[y]=this.ec[x+y]};ha.prototype.getBBox=function(da){var aa=new pa.a;aa.Vg(this.ec,this.Tk,this.Aa,this.nb,0);if(aa.Rl()){var x=this.ec[this.Dd+3],y=this.ec[this.Dd+4];if(x>y){var h=x;x=y;y=h}h=new ka.a;aa.getBBox(h);aa=h.y1<h.y2?h.y1:h.y2;h=h.y1>h.y2?h.y1:h.y2;da[0]=
x;da[1]=aa;da[2]=y;da[3]=h}else{x=1.79769E308;y=ma.a.MIN;aa=1.79769E308;h=ma.a.MIN;for(var e=this.Dd+3,b=0;4>b;++b){var a=this.ec[e+2*b],f=this.ec[e+2*b+1];x=Math.min(x,a);y=Math.max(y,a);aa=Math.min(aa,f);h=Math.max(h,f)}da[0]=x;da[1]=aa;da[2]=y;da[3]=h}};return ha}();ua.a=Ba}}]);}).call(this || window)
