/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{438:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),ha=r(147);Ba=r(49);var da=r(94),aa=r(245),x=r(70),y=r(244);r=r(372);var h=window,e=function(){function f(n,z,w){var ea=-1===n.indexOf("?")?"?":"&";switch(z){case x.a.NEVER_CACHE:this.url=n+ea+"_="+Object(ka.uniqueId)();break;default:this.url=n}this.df=w;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}f.prototype.start=function(n,z){var w=this,ea=this,ja=this.request,ba;ea.jx=0;n&&Object.keys(n).forEach(function(ca){w.request.setRequestHeader(ca,n[ca])});z&&(this.request.withCredentials=z);this.eE=setInterval(function(){var ca=0===window.document.URL.indexOf("file:///");ca=200===ja.status||
ca&&0===ja.status;if(ja.readyState!==y.b.DONE||ca){try{ja.responseText}catch(ia){return}ea.jx<ja.responseText.length&&(ba=ea.aha())&&ea.trigger(f.Events.DATA,[ba]);0===ja.readyState&&(clearInterval(ea.eE),ea.trigger(f.Events.DONE))}else clearInterval(ea.eE),ea.trigger(f.Events.DONE,["Error received return status "+ja.status])},1E3);this.request.send(null);this.status=y.a.STARTED};f.prototype.aha=function(){var n=this.request,z=n.responseText;if(0!==z.length)if(this.jx===z.length)clearInterval(this.eE),
this.trigger(f.Events.DONE);else return z=Math.min(this.jx+3E6,z.length),n=h.QT(n,this.jx,!0,z),this.jx=z,n};f.prototype.abort=function(){clearInterval(this.eE);var n=this;this.request.onreadystatechange=function(){Object(ma.j)("StreamingRequest aborted");n.status=y.a.ABORTED;return n.trigger(f.Events.ABORTED)};this.request.abort()};f.prototype.finish=function(){var n=this;this.request.onreadystatechange=function(){n.status=y.a.SUCCESS;return n.trigger(f.Events.DONE)};this.request.abort()};f.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return f}();Object(Ba.a)(e);var b;(function(f){f[f.LOCAL_HEADER=0]="LOCAL_HEADER";f[f.FILE=1]="FILE";f[f.CENTRAL_DIR=2]="CENTRAL_DIR"})(b||(b={}));var a=function(f){function n(){var z=f.call(this)||this;z.buffer="";z.state=b.LOCAL_HEADER;z.SM=4;z.Tl=null;z.st=ha.c;z.Dn={};return z}Object(pa.c)(n,f);n.prototype.Uga=function(z){var w;for(z=this.buffer+z;z.length>=this.st;)switch(this.state){case b.LOCAL_HEADER:this.Tl=w=this.eha(z.slice(0,this.st));if(w.$t!==
ha.g)throw Error("Wrong signature in local header: "+w.$t);z=z.slice(this.st);this.state=b.FILE;this.st=w.tH+w.vq+w.ew+this.SM;this.trigger(n.Events.HEADER,[w]);break;case b.FILE:this.Tl.name=z.slice(0,this.Tl.vq);this.Dn[this.Tl.name]=this.Tl;w=this.st-this.SM;var ea=z.slice(this.Tl.vq+this.Tl.ew,w);this.trigger(n.Events.FILE,[this.Tl.name,ea,this.Tl.LH]);z=z.slice(w);if(z.slice(0,this.SM)===ha.h)this.state=b.LOCAL_HEADER,this.st=ha.c;else return this.state=b.CENTRAL_DIR,!0}this.buffer=z;return!1};
n.Events={HEADER:"header",FILE:"file"};return n}(aa.a);Object(Ba.a)(a);Ba=function(f){function n(z,w,ea,ja,ba){ea=f.call(this,z,ea,ja)||this;ea.url=z;ea.stream=new e(z,w);ea.Zd=new a;ea.SW=window.createPromiseCapability();ea.tX={};ea.df=ba;return ea}Object(pa.c)(n,f);n.prototype.Zx=function(z){var w=this;this.request([this.rj,this.Ik,this.qj]);this.stream.addEventListener(e.Events.DATA,function(ea){try{if(w.Zd.Uga(ea))return w.stream.finish()}catch(ja){throw w.stream.abort(),w.aw(ja),z(ja),ja;}});
this.stream.addEventListener(e.Events.DONE,function(ea){w.yga=!0;w.SW.resolve();ea&&(w.aw(ea),z(ea))});this.Zd.addEventListener(a.Events.HEADER,Object(ka.bind)(this.sX,this));this.Zd.addEventListener(a.Events.FILE,Object(ka.bind)(this.uha,this));return this.stream.start(this.df,this.withCredentials)};n.prototype.MT=function(z){var w=this;this.SW.promise.then(function(){z(Object.keys(w.Zd.Dn))})};n.prototype.mo=function(){return!0};n.prototype.request=function(z){var w=this;this.yga&&z.forEach(function(ea){w.tX[ea]||
w.ema(ea)})};n.prototype.sX=function(){};n.prototype.abort=function(){this.stream&&this.stream.abort()};n.prototype.ema=function(z){this.trigger(da.a.Events.PART_READY,[{Ya:z,error:"Requested part not found",Bi:!1,Uf:!1}])};n.prototype.uha=function(z,w,ea){this.tX[z]=!0;this.trigger(da.a.Events.PART_READY,[{Ya:z,data:w,Bi:!1,Uf:!1,error:null,ad:ea}])};return n}(da.a);Object(r.a)(Ba);Object(r.b)(Ba);ua["default"]=Ba}}]);}).call(this || window)
