/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[16],{440:function(Ba,ua,r){function pa(){return!1}function ka(z,w,ea){if(!(w in n))return!0;w=n[w];for(var ja=0;ja<w.length;ja++){var ba=z;var ca=w[ja];var ia=ea;if(ca.name in ba){var fa="",la=!1;ba=ba[ca.name];switch(ca.type){case "s":fa="String";la=Object(ha.isString)(ba);break;case "a":fa="Array";la=Object(ha.isArray)(ba);break;case "n":fa="Number";la=Object(ha.isNumber)(ba)&&Object(ha.isFinite)(ba);break;case "o":fa="Object",
la=Object(ha.isObject)(ba)&&!Object(ha.isArray)(ba)}la||ia.reject('Expected response field "'+ca.name+'" to have type '+fa);ca=la}else ia.reject('Response missing field "'+ca.name+'"'),ca=!1;if(!ca)return!1}return!0}r.r(ua);var ma=r(1),ha=r(0);r.n(ha);var da=r(2);Ba=r(49);var aa=r(32),x=r(458),y=r(94),h=r(372),e=r(40),b=r(165),a=function(){function z(){this.request=this.result=null;this.state=0;var w=this;w.promise=new Promise(function(ea,ja){w.resolve=function(){if(0===w.state||4===w.state)w.state=
1,w.result=arguments[0],ea.apply(null,arguments)};w.reject=function(){if(0===w.state||4===w.state)w.state=2,ja.apply(null,arguments)}})}z.prototype.et=function(){return 1===(this.state&1)};z.prototype.fea=function(){return 2===(this.state&2)};z.prototype.Oi=function(){return!this.fea()&&!this.et()};z.prototype.Hda=function(){return 4===(this.state&4)};z.prototype.oM=function(){this.state|=4};return z}(),f=function(){function z(){this.Os={};this.Fb=[]}z.prototype.pop=function(){var w=this.Fb.pop();
this.Os[w.key]=void 0;return w};z.prototype.push=function(w,ea){ea={key:w,data:ea};this.Fb.push(ea);this.Os[w]=ea.data};z.prototype.contains=function(w){return!!this.Os[w]};z.prototype.get=function(w){return this.Os[w]};z.prototype.set=function(w,ea){var ja=this;this.Os[w]=ea;this.Fb.forEach(function(ba,ca){ba.key===w&&(ja.Fb[ca]=ba)})};z.prototype.remove=function(w){var ea=this;this.Os[w]=void 0;this.Fb.forEach(function(ja,ba){ja.key===w&&ea.Fb.splice(ba,1)})};z.prototype.length=function(){return this.Fb.length};
return z}(),n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},
{name:"rID",type:"s"}]};r=function(){function z(w,ea,ja){var ba=this;this.TM=this.gS=!1;this.bh=this.oF=this.qu=this.PK=this.vH=this.Bm=null;this.am=new a;this.wp=new a;this.sB=!1;this.vf=this.ze=this.Ae=this.mf=null;this.Jf=[];this.eC=[];this.cache={};this.timeStamp=0;this.Xg=[];this.Zi=[];this.yI=null;this.VR=!1;this.vY=this.id=null;this.CK=this.uU=pa;this.Yh=0;this.HJ=!1;this.ZV=1;this.Ui={};this.Lr=0;this.It=new f;ea.endsWith("/")||(ea+="/");ja=ja||{};this.gS=ja.disableWebsockets||!1;this.TM=
ja.singleServerMode||!1;null!=ja.customQueryParameters&&Object(e.b)("wvsQueryParameters",ja.customQueryParameters);ea.endsWith("blackbox/")||(ea+="blackbox/");this.Bm=ja.uploadData||null;this.qu=ja.uriData||null;this.vH=ja.cacheKey||null;this.PK=ja.officeOptions||null;this.Se=ea;this.aI=w;this.uo(!0);this.$r=(new x.a(ea,null,this.Jh())).Y$(!this.gS,function(ca){ba.yfa(ca)},function(){return null},function(){ba.sB=!1},function(){ba.Dia()})}z.prototype.G7=function(){var w=this;return new Promise(function(ea,
ja){var ba=new XMLHttpRequest;ba.open("GET",w.Se+"ck");ba.withCredentials=w.Jh();ba.onreadystatechange=function(){ba.readyState===XMLHttpRequest.DONE&&(200===ba.status?ea():ja())};ba.send()})};z.prototype.fka=function(w){this.uU=w||pa;this.CK=pa};z.prototype.m6=function(){this.$X();return this.$r.Hp(!0)};z.prototype.$X=function(){Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return this.wp=new a,this.am=new a,this.sB=!1,this.id=null,this.VR=
!1,[4,this.G7()];case 1:return w.ea(),[2]}})})};z.prototype.Dia=function(){this.uU();this.$X();this.mf&&(this.mf.Oi()?this.jh(this.mf.request):this.mf.et()&&this.CK(this.mf.result.url,"pdf")&&(this.mf=null,this.ZX()));this.vf&&this.vf.Oi()&&this.jh(this.vf.request);this.Ae&&this.Ae.Oi()?this.jh(this.Ae.request):this.ze&&this.ze.Oi()&&this.hU();var w;for(w=0;w<this.Xg.length;w++)this.Xg[w]&&(this.Xg[w].Oi()?this.jh(this.Xg[w].request):this.Xg[w].et()&&this.CK(this.Xg[w].result.url,"image")&&(this.Xg[w]=
null,this.pE(Object(ha.uniqueId)(),w)));for(w=0;w<this.Zi.length;w++)this.Zi[w]&&this.Zi[w].Oi()&&!this.Zi[w].Hda()&&this.jh(this.Zi[w].request);for(w=0;w<this.Jf.length;w++)this.Jf[w]&&this.Jf[w].Oi()&&this.jh(this.Jf[w].request)};z.prototype.rda=function(){return this.sB?Promise.resolve():(this.sB=!0,this.timeStamp=Date.now(),this.$r.aD())};z.prototype.Ama=function(){var w=this,ea,ja,ba,ca,ia;return new Promise(function(fa,la){if(w.Bm)ea=new FormData,ea.append("file",w.Bm.fileHandle,w.Bm.fileHandle.name),
ja=w.Bm.loadCallback,ca="upload",ba=w.Bm.extension;else if(w.qu)ea={uri:w.qu.uri,lqa:w.qu.shareId},ea=Object.keys(ea).map(function(ra){return ra+"="+(ea[ra]?encodeURIComponent(ea[ra]):"")}).join("&"),ia="application/x-www-form-urlencoded; charset=UTF-8",ja=w.qu.loadCallback,ca="url",ba=w.qu.extension;else{fa();return}var na=new XMLHttpRequest,qa=Object(aa.j)(w.Se,"AuxUpload");qa=Object(b.a)(qa,{type:ca,ext:ba});na.open("POST",qa);na.withCredentials=w.Jh();ia&&na.setRequestHeader("Content-Type",ia);
na.addEventListener("load",function(){if(na.readyState===na.DONE&&200===na.status){var ra=JSON.parse(na.response);w.aI=ra.uri;ja(ra);fa(ra)}});na.addEventListener("error",function(){la(na.statusText+" "+JSON.stringify(na))});w.Bm&&null!=w.Bm.onProgress&&(na.upload.onprogress=function(ra){w.Bm.onProgress(ra)});na.send(ea)})};z.prototype.uia=function(w){this.password=w||null;this.am.et()||(this.am=new a,this.jh({t:"pages"}));return this.am.promise};z.prototype.Zx=function(w){this.yI=w||null;this.am.et()||
this.jh({t:"pages"});return this.am.promise};z.prototype.Lv=function(w){w=Object.assign(w,{uri:encodeURIComponent(this.aI)});this.yI&&(w.ext=this.yI);this.bh&&(w.c=this.bh);this.password&&(w.pswd=this.password);this.vH&&(w.cacheKey=this.vH);this.PK&&(w.officeOptions=this.PK);return w};z.prototype.aja=function(){0<this.It.length()&&10>=this.Lr&&this.bja(this.It.pop().data)};z.prototype.N5=function(w){0<this.It.length()&&this.It.contains(w)&&this.It.remove(w)};z.prototype.jh=function(w){w=this.Lv(w);
this.$r.send(w)};z.prototype.rY=function(w,ea){10<this.Lr?this.It.push(w,ea):(this.Lr++,w=this.Lv(ea),this.$r.send(w))};z.prototype.bja=function(w){this.Lr++;w=this.Lv(w);this.$r.send(w)};z.prototype.kl=function(w){return w};z.prototype.tU=function(w){this.TM&&w?Object(da.j)("Server failed health check. Single server mode ignoring check."):!this.Poa&&w&&3>=this.Yh?(this.HJ=!0,this.$r.Hp()):3<this.Yh&&(this.TM=!0)};z.prototype.yfa=function(w){var ea=this,ja=w.data,ba=w.err,ca=w.t;switch(ca){case "upload":ba?
this.Bma.reject(ba):this.Bma.resolve("Success");break;case "pages":ba?this.am.reject(ba):ka(ja,ca,this.am)&&this.am.resolve(ja);break;case "config":if(ba)this.wp.reject(ba);else if(ka(ja,ca,this.wp)){this.tU(ja.unhealthy);ja.id&&(this.id=ja.id);if(ja.auth){var ia=Object(e.a)("wvsQueryParameters");ia.auth=ja.auth;Object(e.b)("wvsQueryParameters",ia)}ja.serverVersion&&(this.oF=ja.serverVersion,Object(da.h)("[WebViewer Server] server version: "+this.oF));ja.serverID?(this.Yh=ja.serverID===this.vY&&this.HJ?
this.Yh+1:0,this.vY=ja.serverID):this.Yh=0;this.HJ=!1;this.wp.resolve(ja)}break;case "health":ba?this.wp.reject(ba):ka(ja,ca,this.wp)&&this.tU(ja.unhealthy);break;case "pdf":ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url));ba?this.mf.reject(ba):ka(ja,ca,this.mf)&&this.mf.resolve(ja);break;case "ApString2Xod":ja.url=Object(b.a)(this.Se+"../data/"+encodeURI(ja.url));ba?this.Ui[ja.rID].reject(ba):ka(ja,ca,this.Ui[ja.rID])&&this.Ui[ja.rID].resolve(ja);break;case "docmod":ja.url=Object(b.a)(this.Se+
"../"+encodeURI(ja.url));ba?this.Ui[ja.rID].reject(ba):ka(ja,ca,this.mf)&&this.Ui[ja.rID].resolve(ja);break;case "xod":if(ba)this.Ae&&this.Ae.Oi()&&this.Ae.reject(ba),this.ze&&this.ze.Oi()&&this.ze.reject(ba);else if(ja.notFound)ja.noCreate||this.Ae&&this.Ae.Oi()&&this.Ae.resolve(ja),this.ze&&this.ze.Oi()&&this.ze.resolve(ja);else{ja.url&&(ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url)));if(!this.ze||this.ze.et())this.ze=new a,this.ze.request={t:"xod",noCreate:!0};this.Ae||(this.Ae=new a,this.Ae.request=
{t:"xod"});this.ze.resolve(ja);this.Ae.resolve(ja)}break;case "cAnnots":ia=this.vf;if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){ia.oM();var fa=[],la=ja.annots;ja=function(oa){var wa=la[oa].s,Da=la[oa].e,Ia=na.Se+"../"+encodeURI(la[oa].xfdf),Ma="true"===la[oa].hasAppearance?Object(b.a)(Ia+".xodapp"):null,Ca=Object(ha.range)(wa,Da+1);fa[oa]={range:Ca,promise:new Promise(function(La,Ra){var Ka=new XMLHttpRequest;Ka.open("GET",Object(b.a)(Ia));Ka.responseType="text";Ka.withCredentials=ea.Jh();Ka.addEventListener("load",
function(){Ka.readyState===Ka.DONE&&200===Ka.status&&La({fr:Ka.response,$k:Ma,range:Ca})});Ka.addEventListener("error",function(){Ra(Ka.statusText+" "+JSON.stringify(Ka))});Ka.send()})}};var na=this;for(ba=0;ba<la.length;ba++)ja(ba);ia.resolve(fa)}break;case "annots":if(ba)this.vf.reject(ba);else if(ka(ja,ca,this.vf)){this.vf.oM();var qa=new XMLHttpRequest;ia=this.Se+"../"+encodeURI(ja.url);var ra=ja.hasAppearance?Object(b.a)(ia+".xodapp"):null;qa.open("GET",Object(b.a)(ia));qa.responseType="text";
qa.withCredentials=this.Jh();qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ea.vf.resolve({fr:qa.response,$k:ra})});qa.addEventListener("error",function(){ea.vf.reject(qa.statusText+" "+JSON.stringify(qa))});qa.send()}break;case "image":this.Lr--;var ta=this.Xg[ja.p];ba?ta.promise.reject(ba):ka(ja,ca,ta)&&(ta.result=ja,ta.result.url=Object(b.a)(this.Se+"../"+encodeURI(ta.result.url)),ta.resolve(ta.result));break;case "tiles":this.Lr--;ta=ja.rID;ia=this.Jf[ta];this.Jf[ta]=
null;this.eC.push(ta);if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){for(ba=0;ba<ja.tiles.length;ba++)ja.tiles[ba]=Object(b.a)(this.Se+"../"+encodeURI(ja.tiles[ba]));ia.resolve(ja)}break;case "text":ta=this.Zi[ja.p];if(ba)ta.reject(ba);else if(ka(ja,ca,ta)){ta.oM();var va=new XMLHttpRequest;ja=Object(b.a)(this.Se+"../"+encodeURI(ja.url));va.open("GET",ja);va.withCredentials=this.Jh();va.addEventListener("load",function(){va.readyState===va.DONE&&200===va.status&&(ta.result=JSON.parse(va.response),ta.resolve(ta.result))});
va.addEventListener("error",function(oa){ta.reject(va.statusText+" "+JSON.stringify(oa))});va.send()}break;case "progress":"loading"===ja.t&&this.trigger(y.a.Events.DOCUMENT_LOADING_PROGRESS,[ja.bytes,ja.total])}this.aja();!ca&&w.echo&&w&&"apstring2xod"===w.echo.t&&(w=w.echo.reqID)&&(2<=parseInt(this.oF,10)?this.Ui[w].reject("Message unhandled by server"):this.Ui[w].reject())};z.prototype.Daa=function(){return Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return[4,
this.rda()];case 1:return w.ea(),[2,this.wp.promise]}})})};z.prototype.maa=function(w){for(var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),ca=new FormData,ia={},fa=0;fa<w.body.length;fa++){var la=w.body[fa];ia[la.id]=la.iH.w+";"+la.iH.h;ca.append(la.id,la.iH.dataString)}w={t:"apstring2xod",reqID:this.ZV++,parts:ia};var na=this.Lv(w);ca.append("msg",JSON.stringify(na));this.Ui[na.reqID]=new a;ja.open("POST",ba);ja.withCredentials=this.Jh;ba=new Promise(function(qa,ra){ja.onreadystatechange=
function(){4===ja.readyState&&(200===ja.status?qa():ra("An error occurred while sending down appearance strings to the server"))}});ja.send(ca);return ba.then(function(){return ea.Ui[na.reqID].promise})};z.prototype.o6=function(){var w=this.oF.split("-")[0].split("."),ea=["1","5","9"];if(3!==w.length)throw Error("Invalid WVS version length.");if(3!==ea.length)throw Error("Invalid version length.");for(var ja=0;ja<w.length;++ja){if(ea.length===ja||w[ja]>ea[ja])return-1;if(w[ja]!==ea[ja])return 1}return 0};
z.prototype.sp=function(){return 0>=this.o6()};z.prototype.HI=function(){this.vf||(this.vf=new a,this.sp()?this.vf.request={t:"cAnnots"}:this.vf.request={t:"annots"},this.jh(this.vf.request));return this.vf.promise};z.prototype.pE=function(w,ea){this.Xg[ea]||(this.Xg[ea]=new a,this.Xg[ea].request={t:"image",p:ea},this.rY(w,this.Xg[ea].request));return this.Xg[ea].promise};z.prototype.via=function(w){this.Zi[w]||(this.Zi[w]=new a,this.Zi[w].request={t:"text",p:w},this.jh(this.Zi[w].request));return this.Zi[w].promise};
z.prototype.wia=function(w,ea,ja,ba,ca){var ia=this.Jf.length;this.eC.length&&(ia=this.eC.pop());this.Jf[ia]=new a;this.Jf[ia].request={t:"tiles",p:ea,z:ja,r:ba,size:ca,rID:ia};this.rY(w,this.Jf[ia].request);return this.Jf[ia].promise};z.prototype.ZX=function(){this.mf||(this.mf=new a,this.mf.request={t:"pdf"},this.VR?this.mf.resolve({url:this.aI}):this.jh(this.mf.request));return this.mf.promise};z.prototype.BT=function(w){var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),
ca=new FormData,ia={};w.annots&&(ia.annots="xfdf");w.watermark&&(ia.watermark="png");w.redactions&&(ia.redactions="redact");ia={t:"docmod",reqID:this.ZV++,parts:ia};w.print&&(ia.print=!0);var fa=this.Lv(ia);ca.append("msg",JSON.stringify(fa));return Promise.all([w.annots,w.watermark,w.redactions].map(function(la){return Promise.resolve(la)})).then(function(la){var na=la[0],qa=la[1];la=la[2];na&&ca.append("annots",na);qa&&ca.append("watermark",qa);la&&ca.append("redactions",la);ea.Ui[fa.reqID]=new a;
ja.open("POST",ba);ja.withCredentials=ea.Jh;na=new Promise(function(ra,ta){ja.onreadystatechange=function(){4===ja.readyState&&(200===ja.status?ra():ta("An error occurred while sending down annotation data to the server"))}});ja.send(ca);return na.then(function(){return ea.Ui[fa.reqID].promise})})};z.prototype.hU=function(){this.ze||(this.ze=new a,this.ze.request={t:"xod",noCreate:!0},this.jh(this.ze.request));return this.ze.promise};z.prototype.xia=function(){this.Ae||(this.Ae=new a,this.Ae.request=
{t:"xod"},this.jh(this.Ae.request));return this.Ae.promise};z.prototype.mo=function(){return!0};z.prototype.request=function(){};z.prototype.sX=function(){};z.prototype.abort=function(){for(var w=0;w<this.Jf.length;w++)this.Jf[w]&&(this.Jf[w].resolve(null),this.Jf[w]=null,this.eC.push(w));this.close()};z.prototype.BE=function(w){this.bh=this.bh||{};this.bh.headers=w};z.prototype.uo=function(w){this.bh=this.bh||{};this.bh.internal=this.bh.internal||{};this.bh.internal.withCredentials=w};z.prototype.Jh=
function(){return this.bh&&this.bh.internal?this.bh.internal.withCredentials:null};z.prototype.getFileData=function(){return Promise.reject()};return z}();Object(Ba.a)(r);Object(h.a)(r);Object(h.b)(r);ua["default"]=r},458:function(Ba,ua,r){var pa=r(1),ka=r(2),ma=r(32),ha=r(40),da=r(165),aa=r(112),x=function(){function h(e,b,a,f,n,z){void 0===a&&(a=null);void 0===f&&(f=null);void 0===n&&(n=null);void 0===z&&(z=null);this.GV=!1;this.Yh=0;this.aR=this.Wma(e);this.url=b?this.aR+"/"+b:this.aR+"/ws";this.UH=
a;this.Dx=f;this.Jv=n;this.VL=z}h.prototype.Wma=function(e){var b=e.indexOf("://"),a="ws://";0>b?b=0:(5===b&&(a="wss://"),b+=3);var f=e.lastIndexOf("/");0>f&&(f=e.length);return a+e.slice(b,f)};h.prototype.send=function(e){this.Go.readyState===WebSocket.CLOSED||this.GV||this.Go.send(JSON.stringify(e))};h.prototype.aD=function(){return Object(pa.b)(this,void 0,void 0,function(){var e,b=this;return Object(pa.d)(this,function(){e=Object(ha.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(ha.b)("wvsQueryParameters",
e);return[2,new Promise(function(a,f){var n=Object(da.a)(b.url);b.Go=new WebSocket(n);b.Go.onopen=function(){b.Dx&&b.Dx();a()};b.Go.onerror=function(z){b.GV=!0;f(z)};b.Go.onclose=function(z){var w=z.code;return Object(pa.b)(b,void 0,void 0,function(){var ea=this;return Object(pa.d)(this,function(ja){switch(ja.label){case 0:return this.Jv&&this.Jv(),3E3===w?[3,3]:8>this.Yh++?[4,new Promise(function(ba){return setTimeout(function(){return Object(pa.b)(ea,void 0,void 0,function(){return Object(pa.d)(this,
function(ca){switch(ca.label){case 0:return this.VL(),[4,this.aD()];case 1:return ca.ea(),ba(),[2]}})})},3E3)})]:[3,2];case 1:return ja.ea(),[3,3];case 2:f(aa.a),ja.label=3;case 3:return[2]}})})};b.Go.onmessage=function(z){z&&z.data&&(z=JSON.parse(z.data),z.hb?b.send({hb:!0}):z.end?close():b.UH(z))}})]})})};h.prototype.Hp=function(e){void 0===e&&(e=!1);this.Yh=0;e?this.Go.close(3E3):this.Go.close();return Promise.resolve()};return h}(),y=function(){function h(e,b,a,f,n,z,w){void 0===f&&(f=null);void 0===
n&&(n=null);void 0===z&&(z=null);void 0===w&&(w=null);this.Yh=this.oE=this.id=0;this.Qw=!1;this.request=null;e=this.Tga(e);this.url=b?e+"/"+b+"pf":e+"/pf";this.hF=a;this.UH=f;this.Dx=n;this.Jv=z;this.VL=w}h.prototype.Tga=function(e){var b=e.lastIndexOf("/");0>b&&(b=e.length);return e.slice(0,b)};h.prototype.p7=function(e){e=e.split("\n");for(e[e.length-1]&&e.pop();0<e.length&&3>e[e.length-1].length;)"]"===e.pop()&&(this.id=0);0<e.length&&3>e[0].length&&e.shift();for(var b=0;b<e.length;++b)e[b].endsWith(",")&&
(e[b]=e[b].substr(0,e[b].length-1));return e};h.prototype.iY=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(b){switch(b.label){case 0:return 8>this.Yh++?[4,new Promise(function(a){return setTimeout(function(){e.VL();e.aD();a()},3E3)})]:[3,2];case 1:b.ea(),b.label=2;case 2:return[2]}})})};h.prototype.Vga=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a;return Object(pa.d)(this,function(f){switch(f.label){case 0:b=null,a=0,f.label=
1;case 1:if(!(a<e.length))return[3,6];b=JSON.parse(e[a]);if(!b)return[3,5];if(!b.end)return[3,2];close();return[3,5];case 2:if(!b.id||Number(b.id)===this.id)return[3,4];Object(ka.j)("Reconnecting, new server detected");this.Hp();return[4,this.iY()];case 3:return f.ea(),[3,5];case 4:b.hb&&Number(b.id)===this.id?this.send({hb:!0}):this.Qw||this.UH(b),f.label=5;case 5:return++a,[3,1];case 6:return[2]}})})};h.prototype.vfa=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a,f;return Object(pa.d)(this,
function(n){switch(n.label){case 0:if(!(3<=e.readyState))return[3,2];try{b=e.responseText.length}catch(z){return Object(ka.h)("caught exception"),[2]}if(0<b)try{a=this.p7(e.responseText),0===this.id&&0<a.length&&(f=JSON.parse(a.shift()),this.id=f.id,this.Yh=0),this.Vga(a)}catch(z){}return this.Qw?[3,2]:[4,this.JS()];case 1:n.ea(),n.label=2;case 2:return[2]}})})};h.prototype.JS=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(){return[2,new Promise(function(b,
a){function f(){return Object(pa.b)(e,void 0,void 0,function(){return Object(pa.d)(this,function(z){switch(z.label){case 0:a(),this.Hp(),z.label=1;case 1:return this.Qw&&8>this.Yh?[4,this.iY()]:[3,3];case 2:return z.ea(),[3,1];case 3:return[2]}})})}e.request=new XMLHttpRequest;e.request.withCredentials=e.hF;var n=Object(da.a)(e.url,0!==e.id?{id:String(e.id),uc:String(e.oE)}:{uc:String(e.oE)});e.oE++;e.request.open("GET",n,!0);e.request.setRequestHeader("Cache-Control","no-cache");e.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");e.request.onreadystatechange=function(){e.vfa(e.request)};e.request.addEventListener("error",f);e.request.addEventListener("timeout",f);e.request.addEventListener("load",function(){e.Dx&&e.Dx();b()});e.request.send()})]})})};h.prototype.aD=function(){var e=Object(ha.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(ha.b)("wvsQueryParameters",e);this.oE=this.id=0;this.Qw=!1;return this.JS()};h.prototype.send=function(e){var b=this,a=new XMLHttpRequest;a.withCredentials=this.hF;
var f=Object(da.a)(this.url,{id:String(this.id)}),n=new FormData;n.append("data",JSON.stringify(e));a.addEventListener("error",function(){b.Hp()});a.open("POST",f);a.setRequestHeader("X-Requested-With","XMLHttpRequest");a.send(n)};h.prototype.Hp=function(){this.id=0;this.Qw=!0;this.Jv&&this.Jv();this.request.abort();return Promise.resolve()};return h}();Ba=function(){function h(e,b,a){this.yR=e;this.target=b;this.hF=a}h.prototype.Y$=function(e,b,a,f,n){void 0===e&&(e=!0);void 0===b&&(b=null);void 0===
a&&(a=null);void 0===f&&(f=null);void 0===n&&(n=null);return e?new x(this.yR,this.target,b,a,f,n):new y(this.yR,this.target,this.hF,b,a,f,n)};return h}();ua.a=Ba}}]);}).call(this || window)
